### ISSUE TITLE
Unable to launch XR animator if parent folder name contains a parenthesis

### ISSUE THREAD

**Issue by AsterDaishi** [ButzYung/SystemAnimatorOnline#36]
I am using the windows version of the application. As per title, I found a bug where the program will be prevented to start if the characters "(" or ")" are present in the name of the folder the program is extracted into. Either of those characters by itself or together will prevent it from functioning. The folder I was trying to launch it from was "New folder (2)"

The behaviour is the following:
when launched from inside a folder contained the aforementioned characters, the program will open as normal, but when one clicks the "start" button, loading will hang indefinitely at 99% of the "loading thex" stage.

**Comment by ButzYung** [comment]
Thanks for the info. I have been receiving similar reports of app stuck at 99%, but no one could tell me the steps to reproduce the problem which made it very difficult for me to fix it. You info helps a lot, and I am able to reproduce the problem. For some unknown reasons, when the path has parenthesis, some modules (namely `three.js`) are imported as separated instances, instead of being the same one across of all imports, resulting in some inconsistencies. A workaround has been made and will be available in the next version of XR Animator (v0.16.0).

**Comment by ButzYung** [comment]
Should be fixed now in v0.16.0. Let me know if there is still any issue.

**Comment by AsterDaishi** [comment]
For sure, I'm glad I could be of help! I do understand, it was an unusual issue to find the cause of. I was assuming it was some incompatibility with installed software until I noticed it would launch from some locations but not from others.
Either way, I just tried v0.16.0 and even though I haven't had a chance to test it extensively, the issue at hand does seem to be solved! 
Thank you so much for your work, this is by far the best tracking program I tried so far. The accuracy at which it's able to track finger movements in particular is incredible.
